# egui-cr: splash screen demo — the 2010s-style startup window: a small
# borderless, per-pixel TRANSPARENT window shaped by a PNG (an
# anti-aliased circle with the white "E" on a blue gradient), with a
# cycling status label at the bottom ("инициализация…", "загрузка…").
#
#   Egui::Backend::Sokol.run(                      # window = image:
#     decorations: false,                           # no system chrome
#     transparent: true,                            # alpha 0 = desktop
#     width: 256, height: 256)                      # image is 1:1
#
# The PNG (assets/splash.png, regenerated by scripts/make_splash.py) is
# drawn once over the whole window; everything it leaves transparent
# shows the desktop through. Drag anywhere to move, Esc to close.
# Cross-platform: X11 depth-32 ARGB visual + compositor, Win32 DWM
# blur-behind, macOS non-opaque NSWindow.

require "../src/egui"
require "../src/egui/backend/sokol"

class SplashApp < Egui::App
  SIZE = 256
  SPLASH_PNG = File.join(__DIR__, "..", "assets", "splash.png")

  STATUS = ["инициализация…", "загрузка шрифтов…",
            "загрузка данных…", "почти готово…"]
  STATUS_SECS = 1.2

  @texture : UInt64 = 0_u64
  @status_index = 0
  @status_time = 0.0

  def update(ctx : Egui::Context) : Nil
    screen = ctx.input.screen_rect

    # Load the splash PNG once (needs the GPU up — first update call):
    # as a texture (drawn 1:1) and as a window shape. The shape is the
    # deterministic part — on X11/Win32 the GL swap chain does not
    # deliver framebuffer alpha to the compositor, so a server-side
    # binary shape (XShape / SetWindowRgn) is what actually cuts the
    # window; the texture's own alpha then only matters on platforms
    # where it composites (macOS).
    if @texture.zero?
      @texture = ctx.load_image(SPLASH_PNG)
      if (m = Egui::Backend::Sokol.image_alpha_mask(SPLASH_PNG))
        Egui::SystemPorts::Window.set_shape(m[:mask], m[:width], m[:height])
      end
    end

    # Cycle the status label; a splash always animates, so keep
    # repainting.
    ctx.request_repaint
    if (t = ctx.input.time) - @status_time >= STATUS_SECS
      @status_time = t
      @status_index = (@status_index + 1) % STATUS.size
    end

    painter = ctx.painter
    painter.layer = Egui::Order::Background
    painter.clip = Egui::Rect.infinite

    # Splash image 1:1 over the whole window — its alpha shapes the
    # window (outside the circle is fully transparent).
    unless @texture.zero?
      painter.image(screen, @texture)
    end

    # Status label, bottom-center inside the circle.
    status = STATUS[@status_index]
    font_size = ctx.style.font_size * 0.9
    text_size = ctx.fonts.measure(status, font_size)
    painter.text(
      Egui::Pos2.new(screen.center.x - text_size.x / 2.0,
        screen.bottom - 42.0),
      status, font_size, Egui::Color32.new(255, 255, 255, 255))

    # Drag anywhere moves the window (native WM loop), Esc closes.
    drag = ctx.interact(Egui::Id.from("splash/drag"), screen,
      Egui::Sense.drag, Egui::LayerId.background, screen)
    drag.on_hover_and_drag_cursor(Egui::CursorIcon::Move)
    Egui::SystemPorts::Window.start_drag if drag.drag_started?

    if ctx.input.keys_pressed.includes?(Egui::KeyCode::Escape)
      Egui::SystemPorts::Quit.quit!
    end
  end
end

Egui::Backend::Sokol.run(SplashApp.new,
  title: "egui-cr — splash", width: SplashApp::SIZE, height: SplashApp::SIZE,
  decorations: false, transparent: true)
