# Generates the egui-cr icon artifacts from the design in assets/icon.svg
# (same geometry, drawn with GDI+ so no SVG rasterizer is needed):
#
#   assets/icon.ico   multi-size (16..256, PNG-packed) for packaging/EXE
#   assets/icon.png   512x512 master (visual reference)
#   examples/icon.cr  64x64 RGBA, Base64-embedded, for the gallery's
#                     runtime window icon (Egui::Backend::Sokol.run icon:)
#
# Run from anywhere: powershell -File scripts\make_icon.ps1
Add-Type -AssemblyName System.Drawing

$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$assetsDir = Join-Path $root 'assets'
New-Item -ItemType Directory -Force -Path $assetsDir | Out-Null

function New-IconBitmap([int]$s) {
    $bmp = New-Object System.Drawing.Bitmap($s, $s)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.SmoothingMode = 'AntiAlias'
    $g.TextRenderingHint = 'AntiAlias'
    $g.PixelOffsetMode = 'HighQuality'

    # geometry mirrors icon.svg: inset 16/512, corner 96/512
    $inset  = [double]$s * 16.0 / 512.0
    $radius = [double]$s * 96.0 / 512.0
    $rect = New-Object System.Drawing.RectangleF($inset, $inset,
        ($s - 2.0 * $inset), ($s - 2.0 * $inset))
    $d = 2.0 * $radius
    $path = New-Object System.Drawing.Drawing2D.GraphicsPath
    $path.AddArc($rect.X, $rect.Y, $d, $d, 180, 90)
    $path.AddArc($rect.Right - $d, $rect.Y, $d, $d, 270, 90)
    $path.AddArc($rect.Right - $d, $rect.Bottom - $d, $d, $d, 0, 90)
    $path.AddArc($rect.X, $rect.Bottom - $d, $d, $d, 90, 90)
    $path.CloseFigure()

    $c1 = [System.Drawing.Color]::FromArgb(0x4F, 0xA8, 0xE8)
    $c2 = [System.Drawing.Color]::FromArgb(0x16, 0x68, 0xC4)
    $brush = New-Object System.Drawing.Drawing2D.LinearGradientBrush($rect,
        $c1, $c2, [System.Drawing.Drawing2D.LinearGradientMode]::Vertical)
    $g.FillPath($brush, $path)

    $font = New-Object System.Drawing.Font('Segoe UI',
        ([double]$s * 330.0 / 512.0), [System.Drawing.FontStyle]::Bold,
        [System.Drawing.GraphicsUnit]::Pixel)
    $fmt = [System.Drawing.StringFormat]::GenericTypographic
    $tsize = $g.MeasureString('E', $font, [System.Drawing.PointF]::Empty, $fmt)
    $pos = New-Object System.Drawing.PointF(
        (($s - $tsize.Width) / 2.0), (($s - $tsize.Height) / 2.0))
    $g.DrawString('E', $font, [System.Drawing.Brushes]::White, $pos, $fmt)

    $g.Dispose()
    return $bmp
}

# --- multi-size .ico (PNG entries, Vista+) ----------------------------------
$icoSizes = @(16, 24, 32, 48, 64, 128, 256)
$pngs = @{}
foreach ($s in $icoSizes) {
    $bmp = New-IconBitmap $s
    $ms = New-Object System.IO.MemoryStream
    $bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
    $bmp.Dispose()
    $pngs[$s] = $ms.ToArray()
}

$bw = New-Object System.IO.BinaryWriter(
    [System.IO.File]::Create((Join-Path $assetsDir 'icon.ico')))
$bw.Write([uint16]0); $bw.Write([uint16]1); $bw.Write([uint16]$icoSizes.Count)
$offset = 6 + 16 * $icoSizes.Count
foreach ($s in $icoSizes) {
    $dim = if ($s -ge 256) { 0 } else { $s }   # 0 encodes 256
    $bw.Write([byte]$dim); $bw.Write([byte]$dim)
    $bw.Write([byte]0); $bw.Write([byte]0)     # colors, reserved
    $bw.Write([uint16]1); $bw.Write([uint16]32) # planes, bpp
    $bw.Write([uint32]$pngs[$s].Length); $bw.Write([uint32]$offset)
    $offset += $pngs[$s].Length
}
foreach ($s in $icoSizes) { $bw.Write($pngs[$s]) }
$bw.Close()
Write-Output ("icon.ico   {0} bytes ({1} sizes)" -f (Get-Item (Join-Path $assetsDir 'icon.ico')).Length, $icoSizes.Count)

# --- 512px master PNG --------------------------------------------------------
$bmp512 = New-IconBitmap 512
$bmp512.Save((Join-Path $assetsDir 'icon.png'), [System.Drawing.Imaging.ImageFormat]::Png)
$bmp512.Dispose()
Write-Output "icon.png   512x512 master"

# --- 64x64 RGBA for the gallery's runtime window icon -----------------------
$bmp64 = New-IconBitmap 64
$data = $bmp64.LockBits((New-Object System.Drawing.Rectangle(0, 0, 64, 64)),
    [System.Drawing.Imaging.ImageLockMode]::ReadOnly,
    [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$bgra = New-Object byte[] (64 * 64 * 4)
[System.Runtime.InteropServices.Marshal]::Copy($data.Scan0, $bgra, 0, $bgra.Length)
$bmp64.UnlockBits($data)
$bmp64.Dispose()
$rgba = New-Object byte[] (64 * 64 * 4)
for ($i = 0; $i -lt 64 * 64; $i++) {
    $rgba[4 * $i + 0] = $bgra[4 * $i + 2]   # R
    $rgba[4 * $i + 1] = $bgra[4 * $i + 1]   # G
    $rgba[4 * $i + 2] = $bgra[4 * $i + 0]   # B
    $rgba[4 * $i + 3] = $bgra[4 * $i + 3]   # A
}
$b64 = [Convert]::ToBase64String($rgba)
$lines = for ($i = 0; $i -lt $b64.Length; $i += 96) {
    if ($i + 96 -lt $b64.Length) { $b64.Substring($i, 96) } else { $b64.Substring($i) }
}
$cr = @()
$cr += '# GENERATED by scripts/make_icon.ps1 from the assets/icon.svg design'
$cr += '# — do not edit; rerun the script instead. 64x64 straight RGBA8,'
$cr += '# white "E" on the blue gradient: the gallery window icon.'
$cr += ''
$cr += 'ICON_B64 = <<-DATA'
$cr += $lines
$cr += 'DATA'
$cr += ''
$cr += 'ICON_64_RGBA = Base64.decode(ICON_B64.delete(''\n''))'
[System.IO.File]::WriteAllLines((Join-Path $root 'examples\icon.cr'), $cr)
Write-Output ("icon.cr    {0} lines (64x64 RGBA embed)" -f $lines.Count)
