# egui-cr — immediate-mode GUI for Crystal.
#
# A 1:1 architectural port of egui (Rust):
#
#   RawInput → Context#begin_frame → app update (Ui, widgets) →
#   Context#end_frame → paint commands → backend (sokol_gfx)
#
# The core (this file tree, minus backend/) is platform-pure and
# headless-testable; only src/egui/backend touches native code.

require "set"

require "./egui/math"
require "./egui/runtime"
require "./egui/color"
require "./egui/smart_aim"
require "./egui/history"
require "./egui/galley"
require "./egui/rich_text"
require "./egui/textures"
require "./egui/layer"
require "./egui/id"
require "./egui/sense"
require "./egui/input"
require "./egui/hotkeys"
require "./egui/state"
require "./egui/memory"
require "./egui/painter"
require "./egui/fonts"
require "./egui/cursor_icon"
require "./egui/style"
require "./egui/stylesheet"
require "./egui/theme"
require "./egui/default_theme"
require "./egui/response"
require "./egui/reactive"
require "./egui/layout"
require "./egui/widgets/icons"
require "./egui/widgets/widget"
require "./egui/widgets/styled_part"
require "./egui/widgets/label"
require "./egui/widgets/button"
require "./egui/widgets/checkbox"
require "./egui/widgets/radio_button"
require "./egui/widgets/separator"
require "./egui/widgets/progress_bar"
require "./egui/widgets/spinner"
require "./egui/widgets/hyperlink"
require "./egui/widgets/slider"
require "./egui/widgets/drag_value"
require "./egui/widgets/number_input"
require "./egui/widgets/text_edit"
require "./egui/widgets/textarea"
require "./egui/widgets/hotkey_edit"
require "./egui/widgets/image"
require "./egui/widgets/canvas"
require "./egui/nanosvg_cr"
require "./egui/widgets/svg"
require "./egui/icon"
require "./egui/widgets/color_picker"
require "./egui/widgets/selectable_label"
require "./egui/widgets/select_box"
require "./egui/widgets/toggle_button"
require "./egui/widgets/segmented"
require "./egui/widgets/date_picker"
require "./egui/widgets/collapsing_header"
require "./egui/containers/combo_box"
require "./egui/containers/sidebar"
require "./egui/containers/tabs"
require "./egui/containers/title_bar_tabs"
require "./egui/containers/page"
require "./egui/containers/menu"
require "./egui/containers/context_menu"
require "./egui/containers/scroll_area"
require "./egui/containers/grid"
require "./egui/containers/tree_view"
require "./egui/containers/table"
require "./egui/containers/plot"
require "./egui/containers/window_frame"
require "./egui/router"
require "./egui/cli"
require "./egui/system_ports/system_ports"
require "./egui/terminal/theme"
require "./egui/terminal/cell"
require "./egui/terminal/grid"
require "./egui/terminal/parser"
require "./egui/terminal/term"
require "./egui/terminal/keymap"
require "./egui/terminal/backend"
require "./egui/terminal/config"
require "./egui/terminal/widget"
require "./egui/ui"
require "./egui/app"
require "./egui/ecss"
require "./egui/context"
require "./egui/inspector"
require "./egui/bench"
